# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vector_service.proto\x12\x0evector_service\"\x1b\n\rVectorRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x14\n\x12ListVectorsRequest\":\n\x0eVectorResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04word\x18\x02 \x01(\t\x12\x0e\n\x06vector\x18\x03 \x03(\x02\x32\xb4\x01\n\rVectorService\x12L\n\tGetVector\x12\x1d.vector_service.VectorRequest\x1a\x1e.vector_service.VectorResponse\"\x00\x12U\n\x0bListVectors\x12\".vector_service.ListVectorsRequest\x1a\x1e.vector_service.VectorResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORREQUEST']._serialized_start=40
  _globals['_VECTORREQUEST']._serialized_end=67
  _globals['_LISTVECTORSREQUEST']._serialized_start=69
  _globals['_LISTVECTORSREQUEST']._serialized_end=89
  _globals['_VECTORRESPONSE']._serialized_start=91
  _globals['_VECTORRESPONSE']._serialized_end=149
  _globals['_VECTORSERVICE']._serialized_start=152
  _globals['_VECTORSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
