---
"metadata":
  "timestamp": |-
    2024-11-02T09:06:07.772699
  "prompt": |-
    docker
  "hash_id": |-
    d11b5aba98
"embedding_config":
  "raw_content": |-
    ```yaml
    lista_palavras:
    - docker
    - containerizacao
    - conteiner
    - imagem
    - imagem docker
    - repositorio
    - docker hub
    - dockerfile
    - build
    - run
    - exec
    - docker-compose
    - orquestração
    - kubernetes
    - swarm
    - microservicos
    - arquitetura
    - conteinerização
    - virtualização
    - isolamento
    - consistência
    - portabilidade
    - escalabilidade
    - resiliência
    - automação
    - infraestrutura
    - desenvolvimento
    - implantação
    - CI/CD
    - DevOps
    - ferramentas
    - comandos
    - opções
    - flags
    - volumes
    - redes
    - pontes
    - host
    - none
    - bridge
    - overlay
    - macvlan
    - docker-compose.yml
    - serviços
    - dependências
    - restart
    - healthcheck
    - logs
    - monitoramento
    - segurança
    - privilégios
    - root
    - usuário
    - senha
    - autenticação
    - autorização
    - acesso
    - controle
    - políticas
    - segurança de imagens
    - verificação de integridade
    - assinatura digital
    - imagens oficiais
    - imagens personalizadas
    - imagens multi-arquitetura
    - imagens multi-plataforma
    - Docker Desktop
    - Docker Engine
    - Docker Hub Enterprise
    - Docker Swarm Mode
    - Docker Compose
    - Docker CLI
    - Docker API
    - Docker SDK
    - Docker Registry
    - Docker Trusted Registry
    - Docker Content Trust
    - Docker Notary
    - Docker Scan
    - Docker Bench Security
    - Docker Security Scanning
    - Docker Security Orchestration
    - Docker Security Posture
    - Docker Security Advisor
    - Docker Security Center
    - Docker Security Suite
    - Docker Security Policy
    - Docker Security Profile
    - Docker Security Group
    - Docker Security Role
    - Docker Security Audit
    - Docker Security Compliance
    - Docker Security Best Practices
    - Docker Security Guidelines
    - Docker Security Documentation
    - Docker Security Community
    - Docker Security Forum
    - Docker Security Blog
    - Docker Security Research
    - Docker Security Training
    - Docker Security Certification
    - Docker Security Awareness
    - Docker Security Education
    - Docker Security Awareness Training
    - Docker Security Best Practices Training
    - Docker Security Certification Training
    - Docker Security Awareness Campaign
    - Docker Security Awareness Program
    - Docker Security Incident Response
    - Docker Security Incident Management
    - Docker Security Incident Analysis
    - Docker Security Incident Reporting
    - Docker Security Incident Remediation
    - Docker Security Incident Prevention
    - Docker Security Incident Detection
    - Docker Security Monitoring
    - Docker Security Logging
    - Docker Security Auditing
    - Docker Security Assessment
    - Docker Security Penetration Testing
    - Docker Security Vulnerability Scanning
    - Docker Security Threat Modeling
    - Docker Security Risk Management
    - Docker Security Policy Management
    - Docker Security Compliance Management
    - Docker Security Governance
    - Docker Security Framework
    - Docker Security Standards
    - Docker Security Regulations
    - Docker Security Laws
    - Docker Security Best Practices
    - Docker Security Guidelines
    - Docker Security Documentation
    - Docker Security Community
    - Docker Security Forum
    - Docker Security Blog
    - Docker Security Research
    - Docker Security Training
    - Docker Security Certification
    - Docker Security Awareness
    - Docker Security Education
    - Docker Security Awareness Training
    - Docker Security Best Practices Training
    - Docker Security Certification Training
    - Docker Security Awareness Campaign
    - Docker Security Awareness Program
    - Docker Security Incident Response
    - Docker Security Incident Management
    - Docker Security Incident Analysis
    - Docker Security Incident Reporting
    - Docker Security Incident Remediation
    - Docker Security Incident Prevention
    - Docker Security Incident Detection
    - Docker Security Monitoring
    - Docker Security Logging
    - Docker Security Auditing
    - Docker Security Assessment
    - Docker Security Penetration Testing
    - Docker Security Vulnerability Scanning
    - Docker Security Threat Modeling
    - Docker Security Risk Management
    - Docker Security Policy Management
    - Docker Security Compliance Management
    - Docker Security Governance
    - Docker Security Framework
    - Docker Security Standards
    - Docker Security Regulations
    - Docker Security Laws
    ```
