---
"metadata":
  "timestamp": |-
    2024-11-02T09:06:43.446373
  "prompt": |-
    docker
  "hash_id": |-
    3909858e41
"embedding_config":
  "raw_content": |-
    ```yaml
    lista_palavras:
    - containerizacao
    - conteiner
    - imagem
    - repositorio
    - dockerfile
    - docker-compose
    - orquestração
    - microserviços
    - kubernetes
    - swarm
    - virtualizacao
    - isolamento
    - portabilidade
    - consistencia
    - replicabilidade
    - automacao
    - build
    - push
    - pull
    - run
    - stop
    - start
    - restart
    - exec
    - logs
    - ps
    - rm
    - kill
    - network
    - volume
    - bind-mount
    - named-volume
    - port-mapping
    - ambiente
    - variaveis-de-ambiente
    - dockerhub
    - registry
    - private-registry
    - docker-desktop
    - docker-machine
    - docker-compose.yml
    - multi-stage-builds
    - docker-in-docker
    - docker-swarm-mode
    - docker-swarm-manager
    - docker-swarm-worker
    - docker-stack
    - docker-secrets
    - docker-configs
    - docker-plugins
    - docker-networking
    - overlay-networking
    - bridge-networking
    - macvlan-networking
    - host-networking
    - docker-security
    - docker-security-context
    - docker-user-namespace
    - docker-selinux
    - docker-apparmor
    - docker-capabilities
    - docker-resource-limits
    - docker-healthchecks
    - docker-restart-policy
    - docker-logging
    - docker-logging-driver
    - docker-logging-configuration
    - docker-monitoring
    - docker-metrics
    - docker-statistics
    - docker-troubleshooting
    - docker-debugging
    - docker-best-practices
    - docker-optimization
    - docker-performance
    - docker-scaling
    - docker-high-availability
    - docker-disaster-recovery
    - docker-ci-cd
    - docker-devops
    - docker-cloud
    - docker-cloud-providers
    - docker-aws
    - docker-azure
    - docker-gcp
    - docker-serverless
    - docker-functions
    - docker-lambda
    - docker-knative
    - docker-istio
    - docker-service-mesh
    - docker-observability
    - docker-tracing
    - docker-logging
    - docker-monitoring
    - docker-security-scanning
    - docker-vulnerability-scanning
    - docker-image-scanning
    - docker-container-scanning
    - docker-compliance
    - docker-governance
    - docker-policy-as-code
    - docker-security-best-practices
    - docker-security-tools
    - docker-security-auditing
    - docker-security-analysis
    - docker-security-monitoring
    - docker-security-incident-response
    - docker-security-training
    - docker-security-awareness
    - docker-security-culture
    - docker-security-management
    - docker-security-framework
    - docker-security-standards
    - docker-security-compliance
    - docker-security-certification
    - docker-security-best-practices
    - docker-security-tools
    - docker-security-auditing
    - docker-security-analysis
    - docker-security-monitoring
    - docker-security-incident-response
    - docker-security-training
    - docker-security-awareness
    - docker-security-culture
    - docker-security-management
    - docker-security-framework
    - docker-security-standards
    - docker-security-compliance
    - docker-security-certification
    ```
