name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t vector-server:latest .
    - name: Push Docker image to registry
      run: docker push ghcr.io/${{ github.repository }}/vector-server:latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to staging
      run: kubectl apply -f deployment.yaml

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
    - name: Deploy to production
      run: kubectl apply -f deployment.yaml # This will need adjustments for production environment
